export class AiChatMessage {
  /**
   * The unique identifier for the AI chat message
   */
  declare id: string

  /**
   * The content of the AI chat message
   */
  declare content: string

  /**
   * The timestamp when the AI chat message was created
   */
  declare createdAt: Date

  /**
   * The id of the AI chat this message belongs to
   * This is used to associate the message with a specific AI chat.
   */
  declare aiChatId: string

  /**
   * The role of the message sender, either 'user' or 'assistant'
   * This indicates whether the message was sent by the user or generated by the AI assistant.
   */
  declare role: 'user' | 'assistant'

  /**
   * Defines if the AI Chat is public or private
   * Denormalized field due performance reasons.
   */
  declare visibility: 'public' | 'private'

  /**
   * The owner of the AI chat message
   * This is used to identify the user who created the message.
   * Denormalized field due performance reasons.
   */
  declare owner: string
}
