name: Build and execute tests
on: [push]
jobs:
  build:
    name: Lint, Build and test
    timeout-minutes: 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Recreate JSON Schemas
        run: yarn create-schemas && yarn build # an incremental rebuild is neccessary to use the updated schema
      - name: Test
        run: yarn test:unit
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Jest test results
          path: coverage/junit.xml
          reporter: jest-junit
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          CI: true

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps

      - name: Dockerize
        run: yarn dockerize

      - name: Start from Docker conatiner
        run: docker run -d -rm -name pirat -p 9090:9090 furystack/pi-rat

      - run: yarn test:e2e:install
        name: 'Test Installer'

      - run: yarn test:e2e
        name: 'E2E tests'

      - run: docker logs pi-rat
        if: always()
        name: Dump Docker logs
