name: Build and execute tests
on: [push]
jobs:
  build:
    name: Lint, Build and test
    timeout-minutes: 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 21.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Prettier check
        run: yarn prettier:check
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Recreate JSON Schemas
        run: yarn create-schemas && yarn build # an incremental rebuild is neccessary to use the updated schema
      - name: Test
        run: yarn test:unit
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          CI: true
