name: Docker Image CI

on:
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build --platform linux/arm/v7,linux/arm64,linux/amd64 . --tag furystack/pi-rat:$(date +%s) --tag furystack/pi-rat:latest
      - name: Push Docker image to Dockerhub
        run: docker push furystack/pi-rat
